import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./componets/Footer";
import Navbar from "./componets/Navbar";
import {Providers} from '@/lib/providers'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Providers>
       <div className="flex flex-col h-screen justify-between">
          <Navbar />
          {children}
          <Footer />
        </div>
       </Providers>
        </body>

    </html>
  );
}
